### ISSUE TITLE
All examples don't work for me: all give errors like 'column u.Discriminator' is not found

### ISSUE THREAD

**Issue by strawberryfield** [dotnet/EntityFramework.Docs.it-it#6]
[Immetti qui i commenti]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: a10898c5-abee-1843-cfff-b2707f8a079a
* Version Independent ID: d9399618-488e-20b1-f707-35a191b95cc1
* Content: [Ereditarietà-EF Core](https://docs.microsoft.com/it-it/ef/core/modeling/inheritance#feedback)
* Content Source: [entity-framework/core/modeling/inheritance.md](https://github.com/dotnet/EntityFramework.Docs.it-it/blob/live/entity-framework/core/modeling/inheritance.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by srvbpigh** [comment]
Hello, @strawberryfield
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @strawberryfield, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/EntityFramework.Docs/issues/2254. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
